import sqlite3
import json
import os
import uuid

db_path = r'restaurant.db'

# Data extracted from AddressStructure.jsx
country_address_hierarchy = {
    "Afghanistan": ["Province", "District", "Area"],
    "Albania": ["County", "Municipality", "Area"],
    "Algeria": ["Province", "District", "Area"],
    "Andorra": ["Parish", "Area", "N/A"],
    "Angola": ["Province", "Municipality", "Area"],
    "Antigua and Barbuda": ["Parish", "Area", "N/A"],
    "Argentina": ["Province", "Department", "Municipality"],
    "Armenia": ["Province", "Community", "Area"],
    "Australia": ["State/Territory", "Local Government Area", "Suburb"],
    "Austria": ["State", "District", "Municipality"],
    "Azerbaijan": ["Economic Region", "District", "Area"],
    "Bahamas": ["District", "Area", "N/A"],
    "Bahrain": ["Governorate", "Municipality", "Area"],
    "Bangladesh": ["Division", "District", "Upazila"],
    "Barbados": ["Parish", "Area", "N/A"],
    "Belarus": ["Region", "District", "Area"],
    "Belgium": ["Region", "Province", "Municipality"],
    "Belize": ["District", "Town", "Area"],
    "Benin": ["Department", "Commune", "Area"],
    "Bhutan": ["District", "Gewog", "Village"],
    "Bolivia": ["Department", "Province", "Municipality"],
    "Bosnia and Herzegovina": ["Entity", "Canton", "Municipality"],
    "Botswana": ["District", "Sub-District", "Area"],
    "Brazil": ["State", "Municipality", "Neighborhood"],
    "Brunei": ["District", "Mukim", "Village"],
    "Bulgaria": ["Province", "Municipality", "Area"],
    "Burkina Faso": ["Region", "Province", "Commune"],
    "Burundi": ["Province", "Commune", "Area"],
    "Cambodia": ["Province", "District", "Commune"],
    "Cameroon": ["Region", "Division", "Sub-Division"],
    "Canada": ["Province/Territory", "Municipality", "Area"],
    "Cape Verde": ["Municipality", "Area", "N/A"],
    "Central African Republic": ["Prefecture", "Sub-Prefecture", "Area"],
    "Chad": ["Province", "Department", "Area"],
    "Chile": ["Region", "Province", "Commune"],
    "China": ["Province", "Prefecture", "County"],
    "Colombia": ["Department", "Municipality", "Area"],
    "Comoros": ["Island", "Prefecture", "Area"],
    "Costa Rica": ["Province", "Canton", "District"],
    "Croatia": ["County", "Municipality", "Area"],
    "Cuba": ["Province", "Municipality", "Area"],
    "Cyprus": ["District", "Municipality", "Area"],
    "Czech Republic": ["Region", "District", "Municipality"],
    "Denmark": ["Region", "Municipality", "Area"],
    "Djibouti": ["Region", "District", "Area"],
    "Dominica": ["Parish", "Area", "N/A"],
    "Dominican Republic": ["Province", "Municipality", "Area"],
    "Ecuador": ["Province", "Canton", "Parish"],
    "Egypt": ["Governorate", "District", "Area"],
    "El Salvador": ["Department", "Municipality", "Area"],
    "Equatorial Guinea": ["Province", "District", "Area"],
    "Eritrea": ["Region", "Sub-Region", "Area"],
    "Estonia": ["County", "Municipality", "Area"],
    "Eswatini": ["Region", "Inkhundla", "Area"],
    "Ethiopia": ["Region", "Zone", "Woreda"],
    "Fiji": ["Division", "Province", "District"],
    "Finland": ["Region", "Municipality", "Area"],
    "France": ["Region", "Department", "Commune"],
    "Gabon": ["Province", "Department", "Area"],
    "Gambia": ["Region", "District", "Area"],
    "Georgia": ["Region", "Municipality", "Area"],
    "Germany": ["State", "District", "Municipality"],
    "Ghana": ["Region", "District", "Area"],
    "Greece": ["Region", "Municipality", "Area"],
    "Grenada": ["Parish", "Area", "N/A"],
    "Guatemala": ["Department", "Municipality", "Area"],
    "Guinea": ["Region", "Prefecture", "Sub-Prefecture"],
    "Guinea-Bissau": ["Region", "Sector", "Area"],
    "Guyana": ["Region", "Neighborhood Council", "Area"],
    "Haiti": ["Department", "Arrondissement", "Commune"],
    "Honduras": ["Department", "Municipality", "Area"],
    "Hungary": ["County", "District", "Municipality"],
    "Iceland": ["Region", "Municipality", "Area"],
    "India": ["State/UT", "District", "Taluk"],
    "Indonesia": ["Province", "Regency/City", "District"],
    "Iran": ["Province", "County", "District"],
    "Iraq": ["Governorate", "District", "Area"],
    "Ireland": ["County", "Municipality", "Area"],
    "Israel": ["District", "Sub-District", "Area"],
    "Italy": ["Region", "Province", "Municipality"],
    "Jamaica": ["Parish", "Area", "N/A"],
    "Japan": ["Prefecture", "City/Ward", "District"],
    "Jordan": ["Governorate", "District", "Area"],
    "Kazakhstan": ["Region", "District", "Area"],
    "Kenya": ["County", "Sub-County", "Ward"],
    "Kiribati": ["Island", "Council", "Area"],
    "Kuwait": ["Governorate", "Area", "Block"],
    "Kyrgyzstan": ["Region", "District", "Area"],
    "Laos": ["Province", "District", "Village"],
    "Latvia": ["Municipality", "Area", "N/A"],
    "Lebanon": ["Governorate", "District", "Area"],
    "Lesotho": ["District", "Community Council", "Area"],
    "Liberia": ["County", "District", "Area"],
    "Libya": ["District", "Municipality", "Area"],
    "Liechtenstein": ["Municipality", "Area", "N/A"],
    "Lithuania": ["County", "Municipality", "Area"],
    "Luxembourg": ["Canton", "Commune", "Area"],
    "Madagascar": ["Region", "District", "Commune"],
    "Malawi": ["Region", "District", "Area"],
    "Malaysia": ["State", "District", "Mukim"],
    "Maldives": ["Atoll", "Island", "Area"],
    "Mali": ["Region", "Cercle", "Commune"],
    "Malta": ["Region", "Local Council", "Area"],
    "Marshall Islands": ["Atoll", "Municipality", "Area"],
    "Mauritania": ["Region", "Department", "Area"],
    "Mauritius": ["District", "Village", "Area"],
    "Mexico": ["State", "Municipality", "Locality"],
    "Micronesia": ["State", "Municipality", "Area"],
    "Moldova": ["District", "Commune", "Area"],
    "Monaco": ["Commune", "Area", "N/A"],
    "Mongolia": ["Province", "District", "Bag"],
    "Montenegro": ["Municipality", "Area", "N/A"],
    "Morocco": ["Region", "Province", "Commune"],
    "Mozambique": ["Province", "District", "Area"],
    "Myanmar": ["Region/State", "District", "Township"],
    "Namibia": ["Region", "Constituency", "Area"],
    "Nauru": ["District", "Area", "N/A"],
    "Nepal": ["Province", "District", "Municipality"],
    "Netherlands": ["Province", "Municipality", "Area"],
    "New Zealand": ["Region", "District", "Area"],
    "Nicaragua": ["Department", "Municipality", "Area"],
    "Niger": ["Region", "Department", "Commune"],
    "Nigeria": ["State", "Local Government Area", "Ward"],
    "North Korea": ["Province", "County", "Area"],
    "North Macedonia": ["Municipality", "Area", "N/A"],
    "Norway": ["County", "Municipality", "Area"],
    "Oman": ["Governorate", "Wilayat", "Area"],
    "Pakistan": ["Province", "Division", "District"],
    "Palau": ["State", "Area", "N/A"],
    "Panama": ["Province", "District", "Corregimiento"],
    "Papua New Guinea": ["Province", "District", "Area"],
    "Paraguay": ["Department", "District", "Area"],
    "Peru": ["Region", "Province", "District"],
    "Philippines": ["Region", "Province", "City/Municipality"],
    "Poland": ["Voivodeship", "County", "Gmina"],
    "Portugal": ["District", "Municipality", "Parish"],
    "Qatar": ["Municipality", "Zone", "Area"],
    "Romania": ["County", "Municipality", "Area"],
    "Russia": ["Federal Subject", "District", "Municipality"],
    "Rwanda": ["Province", "District", "Sector"],
    "Saint Lucia": ["District", "Area", "N/A"],
    "Samoa": ["District", "Village", "Area"],
    "San Marino": ["Municipality", "Area", "N/A"],
    "Saudi Arabia": ["Province", "Governorate", "Area"],
    "Senegal": ["Region", "Department", "Arrondissement"],
    "Serbia": ["District", "Municipality", "Area"],
    "Seychelles": ["District", "Area", "N/A"],
    "Sierra Leone": ["Province", "District", "Area"],
    "Singapore": ["City-State", "N/A", "N/A"],
    "Slovakia": ["Region", "District", "Municipality"],
    "Slovenia": ["Statistical Region", "Municipality", "Area"],
    "Solomon Islands": ["Province", "Ward", "Area"],
    "Somalia": ["State", "District", "Area"],
    "South Africa": ["Province", "District", "Municipality"],
    "South Korea": ["Province", "City/County", "District"],
    "South Sudan": ["State", "County", "Payam"],
    "Spain": ["Autonomous Community", "Province", "Municipality"],
    "Sri Lanka": ["Province", "District", "Division"],
    "Sudan": ["State", "Locality", "Area"],
    "Suriname": ["District", "Resort", "Area"],
    "Sweden": ["County", "Municipality", "Area"],
    "Switzerland": ["Canton", "Municipality", "Area"],
    "Syria": ["Governorate", "District", "Area"],
    "Taiwan": ["County/City", "District", "Area"],
    "Tajikistan": ["Region", "District", "Area"],
    "Tanzania": ["Region", "District", "Ward"],
    "Thailand": ["Province", "District", "Sub-District"],
    "Togo": ["Region", "Prefecture", "Canton"],
    "Tonga": ["Division", "District", "Area"],
    "Trinidad and Tobago": ["Region", "Municipality", "Area"],
    "Tunisia": ["Governorate", "Delegation", "Sector"],
    "Turkey": ["Province", "District", "Neighborhood"],
    "Turkmenistan": ["Province", "District", "Area"],
    "Tuvalu": ["Island", "Area", "N/A"],
    "Uganda": ["Region", "District", "Sub-County"],
    "Ukraine": ["Oblast", "Raion", "Hromada"],
    "United Arab Emirates": ["Emirate", "City", "Area"],
    "United Kingdom": ["Country", "County", "Borough"],
    "United States": ["State", "County", "City"],
    "Uruguay": ["Department", "Municipality", "Area"],
    "Uzbekistan": ["Region", "District", "Area"],
    "Vanuatu": ["Province", "Municipality", "Area"],
    "Vatican City": ["None", "N/A", "N/A"],
    "Venezuela": ["State", "Municipality", "Parish"],
    "Vietnam": ["Province", "District", "Commune"],
    "Yemen": ["Governorate", "District", "Area"],
    "Zambia": ["Province", "District", "Area"],
    "Zimbabwe": ["Province", "District", "Area"]
}

def migrate():
    print("Starting address structure migration...")
    
    # Connect to the SQLite database with a timeout so it doesn't fail instantly if the server is running
    conn = sqlite3.connect(db_path, timeout=30)
    cur = conn.cursor()

    # Get the global address structure document
    cur.execute("SELECT id, data FROM address_structures WHERE id = 'global'")
    row = cur.fetchone()
    
    if row:
        doc = json.loads(row[1])
    else:
        doc = {"_id": "global", "structure": {"countries": {}}, "linkedValues": {}}

    for country, labels in country_address_hierarchy.items():
        if country not in doc["structure"]["countries"]:
            doc["structure"]["countries"][country] = {
                "field1": {"label": labels[0], "values": []},
                "field2": {"label": labels[1], "values": []},
                "field3": {"label": labels[2], "values": []}
            }
            print(f"Added labels for {country}")

    # Use INSERT OR REPLACE to ensure the record exists or is updated
    cur.execute("INSERT OR REPLACE INTO address_structures (id, data) VALUES ('global', ?)", (json.dumps(doc),))
    conn.commit()
    conn.close()
    print("Address Hierarchy Migration completed successfully.")

if __name__ == "__main__":
    migrate()
